# Generated by Django 5.1.5 on 2025-03-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recetas_app', '0001_initial'),
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('insumo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materia_prima.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('galleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Recetas_app.receta')),
            ],
        ),
    ]
