# Generated by Django 5.1.5 on 2025-03-23 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_galleta', models.CharField(max_length=100, unique=True)),
                ('id_receta', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('galleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventarios.galleta')),
            ],
        ),
    ]
