# Generated by Django 5.1.7 on 2025-04-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recetas_app', '0001_initial'),
        ('materia_prima', '0001_initial'),
        ('produccion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=500)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('insumo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materia_prima.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('galleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Recetas_app.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('justificacion', models.TextField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion_app.lotegalletas')),
            ],
        ),
    ]
