# Generated by Django 5.1.5 on 2025-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
