# Generated by Django 5.1.7 on 2025-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariomaterial',
            name='cantidad',
            field=models.PositiveBigIntegerField(),
        ),
    ]
