# Generated by Django 5.1.7 on 2025-04-04 15:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merma',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),  # Cambiado a un valor numérico
            preserve_default=False,
        ),
    ]
