# Generated by Django 5.1.5 on 2025-04-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='cantidad',
        ),
    ]
