# Generated by Django 5.1.5 on 2025-03-24 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas_app', '0001_initial'),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioproducto',
            name='galleta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Recetas_app.receta'),
        ),
        migrations.DeleteModel(
            name='Galleta',
        ),
    ]
