# Generated by Django 5.1.7 on 2025-04-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_remove_inventarioproducto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
