# Generated by Django 5.1.7 on 2025-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_merma_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariomaterial',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=500),
        ),
    ]
