# Generated by Django 5.1.5 on 2025-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_alter_inventarioproducto_galleta_delete_galleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=255, unique=True)),
                ('unidad_base', models.CharField(max_length=50)),
                ('cantidad_dispomible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
