# Generated by Django 5.1.5 on 2025-03-25 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas_app', '0002_materiaprima_alter_ingredientereceta_insumo_and_more'),
        ('inventarios', '0003_inventariomaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariomaterial',
            old_name='cantidad_dispomible',
            new_name='cantidad_disponible',
        ),
        migrations.RemoveField(
            model_name='inventariomaterial',
            name='nombre_insumo',
        ),
        migrations.RemoveField(
            model_name='inventariomaterial',
            name='unidad_base',
        ),
        migrations.AddField(
            model_name='inventariomaterial',
            name='insumo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Recetas_app.materiaprima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventariomaterial',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
