# Generated by Django 5.1.5 on 2025-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_rename_cantidad_dispomible_inventariomaterial_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariomaterial',
            name='cantidad_disponible',
        ),
        migrations.AddField(
            model_name='inventariomaterial',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
