# Generated by Django 5.1.5 on 2025-03-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_remove_inventariomaterial_cantidad_disponible_and_more'),
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariomaterial',
            name='insumo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materia_prima.materiaprima'),
        ),
    ]
