# Generated by Django 5.1.5 on 2025-04-08 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10)),
                ('user_type', models.CharField(default='usuario', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_user', 'Can view user'), ('add_user', 'Can add user'), ('change_user', 'Can change user'), ('view_dashboard', 'Can view dash'), ('view_inventario_prudcto', 'Can view inventario'), ('view_mareia_prima', 'Can view inventario material'), ('add_materia_prima', 'Can add inventario material'), ('change_materia_prima', 'Can change inventario material'), ('view_lotes_produccion', 'Can view lotes produccion'), ('add_lotes_produccion', 'Can add lotes produccion'), ('add_solicitudes_produccion', 'Can add crear solicitudes produccion'), ('add_produccion_galletas', 'Can add change  produccion galletas'), ('view_provedores', 'Can view provedores'), ('add_provedores', 'Can add provedores'), ('change_provedores', 'Can change provedores'), ('view_recetas', 'Can view recetas'), ('add_recetas', 'Can add recetas'), ('change_recetas', 'Can change recetas'), ('view_ventas', 'Can view ventas'), ('add_ventas', 'Can add ventas'), ('change_ventas', 'Can change ventas')],
            },
        ),
    ]
