# Generated by Django 4.2.20 on 2025-03-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('view_user', 'Can view user'), ('add_user', 'Can add user'), ('change_user', 'Can change user'), ('view_dashboard', 'Can view dash')]},
        ),
    ]
