# Generated by Django 4.2.20 on 2025-04-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('admin_permissions', 'admin actions'), ('user_permissions', 'user actions'), ('client_permissions', 'client actions')]},
        ),
    ]
