# Generated by Django 5.1.7 on 2025-04-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=255, unique=True)),
                ('unidad_base', models.CharField(choices=[('g', 'Gramo'), ('ml', 'Mililitro'), ('ud', 'Unidad')], default='kg', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoteMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateField(auto_now=True)),
                ('fecha_caducidad', models.DateField()),
                ('costo_uniario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='insumo_proveedor', to='provedores.provedor')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='materia_prima.materiaprima')),
            ],
        ),
    ]
