# Generated by Django 5.1.5 on 2025-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIn', models.CharField(max_length=255, unique=True)),
                ('unidad_base', models.CharField(max_length=50)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
