# Generated by Django 5.1.7 on 2025-04-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
