# Generated by Django 5.1.5 on 2025-03-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiaprima',
            old_name='nombreIn',
            new_name='nombre_insumo',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='cantidad_disponible',
        ),
    ]
