# Generated by Django 5.1.7 on 2025-04-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0002_materiaprima_cantidad_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='cantidad_disponible',
        ),
    ]
