# Generated by Django 4.2.20 on 2025-04-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0002_alter_materiaprima_unidad_base_lotemateriaprima'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemateriaprima',
            name='costo_uniario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
