# Generated by Django 5.1.5 on 2025-03-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0002_rename_nombrein_materiaprima_nombre_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_base',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro'), ('cm', 'Centímetro'), ('ud', 'Unidad')], default='kg', max_length=50),
        ),
    ]
