# Generated by Django 5.1.5 on 2025-04-04 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0003_remove_materiaprima_cantidad_disponible'),
        ('provedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_base',
            field=models.CharField(choices=[('g', 'Gramo'), ('ml', 'Mililitro'), ('ud', 'Unidad')], default='kg', max_length=50),
        ),
        migrations.CreateModel(
            name='LoteMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateField(auto_now=True)),
                ('fecha_caducidad', models.DateField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='insumo_proveedor', to='provedores.provedor')),
            ],
        ),
    ]
