# Generated by Django 5.1.5 on 2025-04-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0004_alter_materiaprima_unidad_base_lotemateriaprima'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemateriaprima',
            name='insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='materia_prima.materiaprima'),
            preserve_default=False,
        ),
    ]
