# Generated by Django 5.1.5 on 2025-03-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor_nombre', models.TextField(max_length=100)),
                ('provedor_telefono', models.TextField(max_length=100)),
                ('provedor_identificacionNumero', models.TextField(max_length=100)),
                ('provedor_razonSocial', models.TextField(max_length=100)),
                ('provedor_direccion', models.TextField(max_length=100)),
                ('provedor_email', models.TextField(max_length=100)),
                ('provedor_tipo', models.TextField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
    ]
