<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-07 14:09
=======
# Generated by Django 5.1.5 on 2025-04-08 07:38
>>>>>>> 46339a6db870ecd5a5e43f619051a278544119d9

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recetas_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now=True)),
                ('estatus', models.CharField(choices=[('0', 'Creado'), ('1', 'Pagado'), ('2', 'En preparación'), ('3', 'Listo'), ('4', 'Entregado')], default='0', max_length=1)),
                ('fecha_recoleccion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now=True)),
                ('estatus', models.CharField(choices=[('0', 'Abierto'), ('1', 'Confirmado')], default='0', max_length=1)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_pdf', models.BinaryField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ventas_app.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_unidad', models.CharField(choices=[('pq', 'Paquete'), ('g', 'Gramos'), ('ud', 'Unidad')], default='ud', max_length=2)),
                ('carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_app.carritocompras')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas_app.receta')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_app.venta')),
            ],
        ),
    ]
