# Generated by Django 5.1.5 on 2025-03-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recetas_app', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tipo_unidad', models.CharField(choices=[('pq', 'Paquete'), ('g', 'Gramos'), ('ud', 'Unidad')], default='ud', max_length=50)),
                ('fecha_recoleccion', models.DateField(blank=True, null=True)),
                ('carrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_app.carritocompras')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas_app.receta')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_app.venta')),
            ],
        ),
    ]
