# Generated by Django 5.1.5 on 2025-03-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventadetalle',
            name='fecha_recoleccion',
        ),
    ]
