# Generated by Django 5.1.5 on 2025-03-27 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='fecha_recoleccion',
            field=models.DateField(default=datetime.datetime(2025, 3, 27, 5, 7, 58, 539840, tzinfo=datetime.timezone.utc)),
        ),
    ]
