# Generated by Django 5.1.5 on 2025-03-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
