# Generated by Django 5.1.5 on 2025-04-03 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='estatus',
            field=models.CharField(choices=[('0', 'Abierto'), ('1', 'Confirmado')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estatus',
            field=models.CharField(choices=[('0', 'Creado'), ('1', 'Pagado'), ('2', 'En preparación'), ('3', 'Listo'), ('4', 'Entregado')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_app.carritocompras'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='tipo_unidad',
            field=models.CharField(choices=[('pq', 'Paquete'), ('g', 'Gramos'), ('ud', 'Unidad')], default='ud', max_length=2),
        ),
    ]
