# Generated by Django 4.2.20 on 2025-04-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_carritocompras_estatus'),
    ]

    operations = [
    ]
