# Generated by Django 5.1.5 on 2025-04-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_alter_carritocompras_estatus_alter_venta_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_app.carritocompras'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='ventas_app.venta'),
        ),
    ]
