# Generated by Django 5.1.5 on 2025-03-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_remove_ventadetalle_fecha_recoleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_recoleccion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
