# Generated by Django 5.1.5 on 2025-03-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_ventadetalle_fecha_recoleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='fecha_recoleccion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
