# Generated by Django 5.1.7 on 2025-04-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_carritocompras_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estatus',
            field=models.IntegerField(choices=[('0', 'hecho'), ('1', 'Creado'), ('2', 'Listo'), ('3', 'Entregado')], default='0'),
        ),
    ]
