# Generated by Django 4.2.20 on 2025-04-02 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0003_add_fecha_recoleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_app.carritocompras'),
        ),
    ]
