# Generated by Django 5.1.5 on 2025-03-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0003_alter_ventadetalle_fecha_recoleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='tipo_unidad',
            field=models.CharField(choices=[('pq', 'Paquete'), ('g', 'Gramos'), ('ud', 'Unidad')], default='ud', max_length=50),
        ),
    ]
