# Generated by Django 5.1.5 on 2025-03-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0004_alter_venta_estatus_alter_ventadetalle_tipo_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='total',
            field=models.FloatField(default=100),
        ),
    ]
