# Generated by Django 5.1.5 on 2025-03-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0005_alter_venta_estatus_alter_ventadetalle_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
