# Generated by Django 5.1.7 on 2025-04-01 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad_producida', models.IntegerField()),
                ('cantidad_materia_prima_utilizada', models.IntegerField()),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], default='en_proceso', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia_prima.materiaprima')),
            ],
        ),
    ]
