# Generated by Django 5.1.5 on 2025-04-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteGalletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_lotes', models.PositiveIntegerField(default=1)),
                ('fecha_produccion', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('PREPARANDO', 'Preparando'), ('COCINANDO', 'Cocinando'), ('TERMINADO', 'Terminado')], default='CREADO', max_length=20)),
                ('galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Recetas_app.receta')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now=True)),
                ('galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas_app.receta')),
                ('lote_generado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion_app.lotegalletas')),
            ],
        ),
    ]
