# Generated by Django 5.1.7 on 2025-04-01 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas_app', '0001_initial'),
        ('produccion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='nombre_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas_app.receta'),
        ),
    ]
