# Generated by Django 5.1.5 on 2025-04-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0002_lotegalletas_solicitudproduccion_delete_produccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudproduccion',
            name='usuario',
        ),
    ]
