# Generated by Django 5.1.5 on 2025-03-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_galletas_producidas', models.IntegerField()),
                ('peso_individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_galleta', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'permissions': [('puede_ver_recetas', 'Puede ver recetas')],
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia_prima.materiaprima')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='Recetas_app.receta')),
            ],
        ),
    ]
