# Generated by Django 5.1.5 on 2025-03-26 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas_app', '0001_initial'),
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientereceta',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia_prima.materiaprima'),
        ),
        migrations.DeleteModel(
            name='InsumoTemporal',
        ),
    ]
