# Generated by Django 5.1.7 on 2025-04-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='precio_galleta',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
