# Generated by Django 5.1.5 on 2025-03-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=255, unique=True)),
                ('unidad_base', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredientereceta',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Recetas_app.materiaprima'),
        ),
        migrations.DeleteModel(
            name='InsumoTemporal',
        ),
    ]
