# Generated by Django 5.1.5 on 2025-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas_app', '0002_materiaprima_alter_ingredientereceta_insumo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiaprima',
            old_name='nombre_insumo',
            new_name='nombreIn',
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
