# Generated by Django 5.1.5 on 2025-03-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas_app', '0002_alter_ingredientereceta_insumo_delete_insumotemporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='precio_galleta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
