# Generated by Django 5.1.5 on 2025-03-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas_app', '0003_rename_nombre_insumo_materiaprima_nombrein_and_more'),
        ('inventarios', '0006_alter_inventariomaterial_insumo'),
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientereceta',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia_prima.materiaprima'),
        ),
        migrations.DeleteModel(
            name='MateriaPrima',
        ),
    ]
